import mongoose from 'mongoose';

const teamSchema = new mongoose.Schema({
  name: { type: String, required: true },
  project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true },
  course: { type: mongoose.Schema.Types.ObjectId, ref: 'Course', required: true },
  section: { type: String, default: '' },
  teamLead: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  members: [{
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    joinedAt: { type: Date, default: Date.now },
    role: { type: String, default: 'Member' },
    assignedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    assignedAt: Date,
  }],
  joinRequests: [{
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    status: { type: String, enum: ['pending', 'approved', 'rejected'], default: 'pending' },
    requestedAt: { type: Date, default: Date.now },
    respondedAt: Date,
  }],
  status: { type: String, enum: ['pending', 'active', 'rejected'], default: 'pending' },
  isAutoGenerated: { type: Boolean, default: false },
  generatedAt: Date,
  generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  contributionScores: [{
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    score: Number,
  }],
}, { timestamps: true });

export default mongoose.model('Team', teamSchema);
